### ISSUE TITLE
这里差了一个属性

### ISSUE THREAD

**Issue by gaoconggit** [linianhui/Ids3.demo#1]
ApplicationPool = new ApplicationPoolSettings()
            {
                Name = "ids3-dev",
                IdentityType = IdentityType.LocalSystem,
               //这个属性你的build.cake文件中没写，我本地运行的时候会报错
                MaxProcesses=100 //“MaxProcesses”属性的值必须介于 1 和 2147483647 之间(含)。

            }

**Comment by linianhui** [comment]
嗯，我看来一下，默认应该会有个值，可能是你本机的Config没有去到这个值：
``` csharp
// Microsoft.Web.Administration.ApplicationPoolProcessModel
public long MaxProcesses
{
	get
	{
		return (long)base.GetAttributeValue("maxProcesses");
	}
	set
	{
		if (value < 0L || value > 2147483647L)
		{
			throw new ArgumentOutOfRangeException("value", string.Format(CultureInfo.CurrentCulture, Resources.UIntArgumentOutOfRange, new object[]
			{
				"MaxProcesses",
				0,
				2147483647
			}));
		}
		base["maxProcesses"] = value;
	}
}
```

我设置个默认的1吧。
